ALTER TABLE `pro` ADD CONSTRAINT FOREIGN KEY(`subscription_id`) REFERENCES subscription(`id`) ON UPDATE CASCADE ON DELETE NO ACTION;
ALTER TABLE `report_pro` ADD CONSTRAINT FOREIGN KEY(`patient_id`) REFERENCES patient(`id`) ON UPDATE CASCADE ON DELETE NO ACTION;
ALTER TABLE `report_pro` ADD CONSTRAINT FOREIGN KEY(`pro_id`) REFERENCES pro(`id`) ON UPDATE CASCADE ON DELETE NO ACTION;
ALTER TABLE `followup` ADD CONSTRAINT FOREIGN KEY(`patient_id`) REFERENCES patient(`id`) ON UPDATE CASCADE ON DELETE NO ACTION;
ALTER TABLE `followup` ADD CONSTRAINT FOREIGN KEY(`pro_id`) REFERENCES pro(`id`) ON UPDATE CASCADE ON DELETE NO ACTION;
ALTER TABLE `followup` ADD CONSTRAINT FOREIGN KEY(`cares_id`) REFERENCES cares(`id`) ON UPDATE CASCADE ON DELETE NO ACTION;
ALTER TABLE `diary` ADD CONSTRAINT FOREIGN KEY(`patient_id`) REFERENCES patient(`id`) ON UPDATE CASCADE ON DELETE NO ACTION;
ALTER TABLE `diary` ADD CONSTRAINT FOREIGN KEY(`mood_id`) REFERENCES mood(`id`) ON UPDATE CASCADE ON DELETE NO ACTION;

